CREATE TABLE orders (
    OrderID VARCHAR(20) PRIMARY KEY,
    OrderDate VARCHAR(20),
    CustomerID VARCHAR(20),
    Product VARCHAR(50),
    Quantity INT,
    UnitPrice NUMERIC(10,2),
    ShippingAddress VARCHAR(100),
    PaymentMethod VARCHAR(30),
    OrderStatus VARCHAR(30),
    TrackingNumber VARCHAR(30),
    ItemsInCart INT,
    CouponCode VARCHAR(30),
    ReferralSource VARCHAR(30),
    TotalPrice NUMERIC(10,2)
);

ALTER TABLE orders ADD COLUMN order_date DATE;
UPDATE orders
SET order_date = TO_DATE(OrderDate , 'DD-MM-YY');

ALTER TABLE orders DROP COLUMN orderdate;
ALTER TABLE orders RENAME COLUMN order_date TO orderdate;

-- Query 1: Basic SELECT statement
-- Purpose: Display selected columns (OrderID, Product, Quantity, TotalPrice)
SELECT orderid , product ,quantity , totalprice FROM orders;

-- Query 2: WHERE clause - filter by exact match
-- Purpose: Retrieve only orders with status 'Delivered
select * FROM orders
WHERE orderstatus = 'Delivered';

-- Query 3: WHERE clause - filter by numeric comparison
-- Purpose: Retrieve orders with total price greater than 1000
Select * FROM orders
WHERE totalprice >1000; 

-- Query 4: WHERE clause - filter by text value
-- Purpose: Retrieve orders where the referral source is 'Instagram' and 'Facebook'
SELECT  orderid , customerid , referralsource 
FROM orders
WHERE referralsource in ('Instagram' , 'Facebook');

-- Query 5: ORDER BY - sort in descending order
-- Purpose: Display orders sorted from highest to lowest total price
SELECT orderid , totalprice
FROM orders
ORDER BY totalprice DESC;

-- Query 6: ORDER BY - sort in ascending order
-- Purpose: Display orders sorted from lowest to highest total price
SELECT orderid , totalprice
FROM orders
ORDER BY totalprice ASC;

-- Query 7: GROUP BY with SUM
-- Purpose: Calculate total revenue generated by each product
SELECT product , SUM(totalprice) AS total_revenue
FROM orders
GROUP BY product
ORDER BY SUM(totalprice) DESC;

-- Query 8: GROUP BY with COUNT
-- Purpose: Count the number of orders for each order status
SELECT orderstatus , COUNT(*) as total_orders
FROM orders
GROUP BY orderstatus
ORDER BY total_orders DESC;

-- Query 9: GROUP BY with AVG (rounded to 2 decimal places)
-- Purpose: Calculate the average order value for each payment method
SELECT paymentmethod , ROUND(AVG(totalprice) , 2) AS avg_total_price
FROM orders
GROUP BY paymentmethod
ORDER BY avg_total_price DESC;

-- Query 10: HAVING clause - filter grouped/aggregated data
-- Purpose: Display only products whose total revenue exceeds 160000
-- Note: WHERE filters rows before grouping; HAVING filters groups after aggregation
SELECT product , SUM(totalprice) AS total_revenue
FROM orders
GROUP BY product
HAVING SUM(totalprice)>160000
ORDER BY SUM(totalprice) DESC;

-- Query 11: Combining WHERE, GROUP BY, and ORDER BY
-- Purpose: Calculate product-wise revenue for only 'Delivered' orders
SELECT  product , SUM(totalprice)  AS total_revenue
FROM orders
WHERE orderstatus = 'Delivered'
GROUP BY product
ORDER BY total_revenue DESC;

-- Query 12: Percentage contribution using a subquery
-- Purpose: Calculate the percentage contribution of each referral source to total orders
SELECT referralsource ,COUNT(*) AS total_orders ,  ROUND(COUNT(*)*100.0/(SELECT COUNT(*) FROM orders) , 2) AS percentage
FROM orders 
GROUP BY referralsource
ORDER BY percentage;

-- Query 13: Coupon usage impact on revenue
-- Purpose: Identify which coupon code generated the highest total revenue
SELECT couponcode , COUNT(*) AS time_used , SUM(totalprice) AS total_revenue
FROM orders
GROUP BY couponcode
ORDER BY total_revenue DESC;
